### ISSUE TITLE
postfix & sendmail conflicts 

### ISSUE THREAD

**Issue by borgmaan** [KHP-Informatics/redcap-docker#2]
Thank you for putting together this excellent repo - it makes creating test environments a snap!

When I try to run `docker build --tag="afolarin/redcap:webapp"` I get the following error:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sendmail : Depends: sendmail-bin but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
INFO[0010] The command [/bin/sh -c apt-get update &&        apt-get -yq install         mysql-server-5.5        php5-mcrypt         postfix         sendmail] returned a non-zero code: 100
```

If you remove `sendmail` from the `apt-get` statement in `web/Dockerfile` and re-build everything seems to work (but I have only began testing). I am on OS X 10.10.3 with this Docker set up:

```
$ boot2docker version
Boot2Docker-cli version: v1.5.0
Git commit: ccd9032

$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Comment by afolarin** [comment]
Thanks borgmaan, that's the principle objectives of redcap-docker, we keep images of different setups -- we use it for a similar testing  purpose.
Actually sendmail is not needed, as postscript is the principle means for satisfying smtp requirement. I'll correct the Dockerfile now.
